### ISSUE TITLE
Ox not running with ruby 2.5.X

### ISSUE THREAD

**Issue by PascalTurbo** [ohler55/ox#210]
After upgrading from 2.4.3 to 2.5.1 Ox throws this strange error:

```
undefined method `new' for #<NoMethodError: undefined method `[]=' for nil:NilClass>
```

Maybe it's sufficient to run integration tests against ruby 2.5.X. If not, I could try to reduce my code to a minimal example (it's a bunch of work because I have to remove some internals).

**Comment by ohler55** [comment]
With seeing more of you code it is hard to say what is going on. It looks like you were doing a load or parse. Somewhere an error was raised. An attempt was then made to call `new` on that error.

Any hints as to what the code is doing? If it is tough to reduce the code, is is possible for me to work with the full project?

**Comment by ohler55** [comment]
Are you still having problems with this. I don't think it is a ruby 2.5.1 issue as Ox passes the travis tests and works on OS X here.

**Comment by ohler55** [comment]
Is this still an issue?

**Comment by ohler55** [comment]
No response, closing.
