### PR TITLE
Support Ruby 4.0 Ractor

### PR DESCRIPTION
**Pull request by Watson1978**
Since Ruby 4.0, it has breaking changes in Ractor.
Ref. https://bugs.ruby-lang.org/issues/21262

sax_ractor.rb does not work with Ruby 4.0.
This PR will fix to work expectedly with Ruby 4.0.

### Before
```
$ ruby -v sax_ractor.rb /usr/share/mime/packages/freedesktop.org.xml image/jpeg font/ttf application/xhtml+xml image/x-pic
ruby 4.0.0dev (2025-11-22T16:48:13Z master dd489ee9c4) +PRISM [x86_64-linux]
Parallel Ractors
sax_ractor.rb:187:in 'block in <main>': undefined method 'take' for an instance of Ractor (NoMethodError)

  [herd[_1], herd[_1].take]
                     ^^^^^
        from sax_ractor.rb:186:in 'Range#each'
        from sax_ractor.rb:186:in 'Enumerable#map'
        from sax_ractor.rb:186:in '<main>'
double free or corruption (fasttop)
[1]    112557 IOT instruction (core dumped)  ruby -v sax_ractor.rb /usr/share/mime/packages/freedesktop.org.xml image/jpeg

```

### After
```
$ ruby -v sax_ractor.rb /usr/share/mime/packages/freedesktop.org.xml image/jpeg font/ttf application/xhtml+xml image/x-pic
ruby 4.0.0dev (2025-11-22T16:48:13Z master dd489ee9c4) +PRISM [x86_64-linux]
Parallel Ractors
["Steer 1 gave us TrueType-skriftipe (font/ttf) [.ttf]",
 "Bull 1 gave us #<Ractor::Port:0x0000150dc609e0c8>",
 "Heifer 1 gave us JPEG-beeld (image/jpeg) [.jpg,.jpeg,.jpe,.jfif]",
 "Bull 2 gave us #<Ractor::Port:0x0000150dc609e0c8>"]

Serial Ractor
"ONLY ONE OX gave us [#<CYO JPEG-beeld (image/jpeg) [.jpg,.jpeg,.jpe,.jfif]>, #<CYO TrueType-skriftipe (font/ttf) [.ttf]>, #<CYO XHTML-bladsy (application/xhtml+xml) [.xhtml,.xht,.html,.htm]>, #<CYO XHTML-bladsy (application/xhtml+xml) [.xhtml,.xht,.html,.htm]>]"
```

### CODE REVIEW

**Review by ohler55 — APPROVED** [review]

**Comment by Watson1978** [comment]
Thanks
