### ISSUE TITLE
Can't compile on MRI 2.5.0

### ISSUE THREAD

**Issue by elia** [ohler55/ox#200]
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/elia/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/ox-2.2.1/ext/ox
/Users/elia/.rvm/rubies/ruby-2.5.0/bin/ruby -r ./siteconf20180214-2625-yawfrr.rb extconf.rb
>>>>> Creating Makefile for ruby version 2.5.0 on x86_64-darwin17 <<<<<
creating Makefile

current directory: /Users/elia/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/ox-2.2.1/ext/ox
make "DESTDIR=" clean

current directory: /Users/elia/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/ox-2.2.1/ext/ox
make "DESTDIR="
compiling base64.c
compiling cache.c
cache.c:30:25: warning: implicit conversion from 'int' to 'char' changes value from 255 to -1 [-Wconstant-conversion]
    *d = (255 <= len) ? 255 : len;
       ~                ^~~
1 warning generated.
compiling cache8.c
compiling cache8_test.c
compiling cache_test.c
compiling dump.c
dump.c:747:30: error: too many arguments to function call, expected 0, have 1
            VALUE       beg = RSTRUCT_PTR(obj)[0];
                              ~~~~~~~~~~~~^~~~
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby/ruby.h:1189:47: note: expanded from macro 'RSTRUCT_PTR'
#define RSTRUCT_PTR(st)         rb_struct_ptr(st)
                                ~~~~~~~~~~~~~ ^~
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby/backward.h:47:1: note: 'rb_struct_ptr' declared here
DECLARE_DEPRECATED_INTERNAL_FEATURE(rb_struct_ptr);
^
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby/backward.h:39:5: note: expanded from macro 'DECLARE_DEPRECATED_INTERNAL_FEATURE'
    NORETURN(ERRORFUNC(("deprecated internal function"), DEPRECATED(void func(void))))
    ^
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/x86_64-darwin17/ruby/config.h:125:21: note: expanded from macro 'NORETURN'
#define NORETURN(x) __attribute__ ((__noreturn__)) x
                    ^
dump.c:747:18: warning: 'rb_struct_ptr' is deprecated [-Wdeprecated-declarations]
            VALUE       beg = RSTRUCT_PTR(obj)[0];
                              ^
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby/ruby.h:1189:33: note: expanded from macro 'RSTRUCT_PTR'
#define RSTRUCT_PTR(st)         rb_struct_ptr(st)
                                ^
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby/backward.h:47:1: note: 'rb_struct_ptr' has been explicitly marked deprecated here
DECLARE_DEPRECATED_INTERNAL_FEATURE(rb_struct_ptr);
^
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby/backward.h:39:58: note: expanded from macro 'DECLARE_DEPRECATED_INTERNAL_FEATURE'
    NORETURN(ERRORFUNC(("deprecated internal function"), DEPRECATED(void func(void))))
                                                         ^
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/x86_64-darwin17/ruby/config.h:126:39: note: expanded from macro 'DEPRECATED'
#define DEPRECATED(x) __attribute__ ((__deprecated__)) x
                                      ^
dump.c:748:30: error: too many arguments to function call, expected 0, have 1
            VALUE       end = RSTRUCT_PTR(obj)[1];
                              ~~~~~~~~~~~~^~~~
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby/ruby.h:1189:47: note: expanded from macro 'RSTRUCT_PTR'
#define RSTRUCT_PTR(st)         rb_struct_ptr(st)
                                ~~~~~~~~~~~~~ ^~
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby/backward.h:47:1: note: 'rb_struct_ptr' declared here
DECLARE_DEPRECATED_INTERNAL_FEATURE(rb_struct_ptr);
^
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby/backward.h:39:5: note: expanded from macro 'DECLARE_DEPRECATED_INTERNAL_FEATURE'
    NORETURN(ERRORFUNC(("deprecated internal function"), DEPRECATED(void func(void))))
    ^
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/x86_64-darwin17/ruby/config.h:125:21: note: expanded from macro 'NORETURN'
#define NORETURN(x) __attribute__ ((__noreturn__)) x
                    ^
dump.c:748:18: warning: 'rb_struct_ptr' is deprecated [-Wdeprecated-declarations]
            VALUE       end = RSTRUCT_PTR(obj)[1];
                              ^
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby/ruby.h:1189:33: note: expanded from macro 'RSTRUCT_PTR'
#define RSTRUCT_PTR(st)         rb_struct_ptr(st)
                                ^
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby/backward.h:47:1: note: 'rb_struct_ptr' has been explicitly marked deprecated here
DECLARE_DEPRECATED_INTERNAL_FEATURE(rb_struct_ptr);
^
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby/backward.h:39:58: note: expanded from macro 'DECLARE_DEPRECATED_INTERNAL_FEATURE'
    NORETURN(ERRORFUNC(("deprecated internal function"), DEPRECATED(void func(void))))
                                                         ^
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/x86_64-darwin17/ruby/config.h:126:39: note: expanded from macro 'DEPRECATED'
#define DEPRECATED(x) __attribute__ ((__deprecated__)) x
                                      ^
dump.c:749:31: error: too many arguments to function call, expected 0, have 1
            VALUE       excl = RSTRUCT_PTR(obj)[2];
                               ~~~~~~~~~~~~^~~~
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby/ruby.h:1189:47: note: expanded from macro 'RSTRUCT_PTR'
#define RSTRUCT_PTR(st)         rb_struct_ptr(st)
                                ~~~~~~~~~~~~~ ^~
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby/backward.h:47:1: note: 'rb_struct_ptr' declared here
DECLARE_DEPRECATED_INTERNAL_FEATURE(rb_struct_ptr);
^
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby/backward.h:39:5: note: expanded from macro 'DECLARE_DEPRECATED_INTERNAL_FEATURE'
    NORETURN(ERRORFUNC(("deprecated internal function"), DEPRECATED(void func(void))))
    ^
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/x86_64-darwin17/ruby/config.h:125:21: note: expanded from macro 'NORETURN'
#define NORETURN(x) __attribute__ ((__noreturn__)) x
                    ^
dump.c:749:19: warning: 'rb_struct_ptr' is deprecated [-Wdeprecated-declarations]
            VALUE       excl = RSTRUCT_PTR(obj)[2];
                               ^
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby/ruby.h:1189:33: note: expanded from macro 'RSTRUCT_PTR'
#define RSTRUCT_PTR(st)         rb_struct_ptr(st)
                                ^
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby/backward.h:47:1: note: 'rb_struct_ptr' has been explicitly marked deprecated here
DECLARE_DEPRECATED_INTERNAL_FEATURE(rb_struct_ptr);
^
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby/backward.h:39:58: note: expanded from macro 'DECLARE_DEPRECATED_INTERNAL_FEATURE'
    NORETURN(ERRORFUNC(("deprecated internal function"), DEPRECATED(void func(void))))
                                                         ^
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/x86_64-darwin17/ruby/config.h:126:39: note: expanded from macro 'DEPRECATED'
#define DEPRECATED(x) __attribute__ ((__deprecated__)) x
                                      ^
dump.c:769:23: warning: 'rb_struct_ptr' is deprecated [-Wdeprecated-declarations]
            for (i = 0, vp = RSTRUCT_PTR(obj); i < cnt; i++, vp++) {
                             ^
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby/ruby.h:1189:33: note: expanded from macro 'RSTRUCT_PTR'
#define RSTRUCT_PTR(st)         rb_struct_ptr(st)
                                ^
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby/backward.h:47:1: note: 'rb_struct_ptr' has been explicitly marked deprecated here
DECLARE_DEPRECATED_INTERNAL_FEATURE(rb_struct_ptr);
^
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby/backward.h:39:58: note: expanded from macro 'DECLARE_DEPRECATED_INTERNAL_FEATURE'
    NORETURN(ERRORFUNC(("deprecated internal function"), DEPRECATED(void func(void))))
                                                         ^
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/x86_64-darwin17/ruby/config.h:126:39: note: expanded from macro 'DEPRECATED'
#define DEPRECATED(x) __attribute__ ((__deprecated__)) x
                                      ^
dump.c:769:35: error: too many arguments to function call, expected 0, have 1
            for (i = 0, vp = RSTRUCT_PTR(obj); i < cnt; i++, vp++) {
                             ~~~~~~~~~~~~^~~~
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby/ruby.h:1189:47: note: expanded from macro 'RSTRUCT_PTR'
#define RSTRUCT_PTR(st)         rb_struct_ptr(st)
                                ~~~~~~~~~~~~~ ^~
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby/backward.h:47:1: note: 'rb_struct_ptr' declared here
DECLARE_DEPRECATED_INTERNAL_FEATURE(rb_struct_ptr);
^
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/ruby/backward.h:39:5: note: expanded from macro 'DECLARE_DEPRECATED_INTERNAL_FEATURE'
    NORETURN(ERRORFUNC(("deprecated internal function"), DEPRECATED(void func(void))))
    ^
/Users/elia/.rvm/rubies/ruby-2.5.0/include/ruby-2.5.0/x86_64-darwin17/ruby/config.h:125:21: note: expanded from macro 'NORETURN'
#define NORETURN(x) __attribute__ ((__noreturn__)) x
                    ^
4 warnings and 4 errors generated.
make: *** [dump.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/elia/.rvm/gems/ruby-2.5.0/gems/ox-2.2.1 for inspection.
Results logged to /Users/elia/.rvm/gems/ruby-2.5.0/extensions/x86_64-darwin-17/2.5.0/ox-2.2.1/gem_make.out

An error occurred while installing ox (2.2.1), and Bundler cannot continue.
Make sure that `gem install ox -v '2.2.1'` succeeds before bundling.
```

**Comment by ohler55** [comment]
Ox version 2.2.1 is almost 3 years old. Please use the latest Ox which is 2.8.2.

**Comment by elia** [comment]
Sorry for the spam, the actual issue is this one https://github.com/cloocher/xmlhasher/pull/8
