### ISSUE TITLE
Fails to build on 2.4.0-preview2

### ISSUE THREAD

**Issue by Zapotek** [ohler55/ox#153]
```
current directory: /home/zapotek/.rvm/gems/ruby-2.4.0-preview2/gems/ox-2.4.5/ext/ox
/home/zapotek/.rvm/rubies/ruby-2.4.0-preview2/bin/ruby -r ./siteconf20161025-2228-1jc5u3z.rb extconf.rb
>>>>> Creating Makefile for ruby version 2.4.0 on x86_64-linux <<<<<
creating Makefile

current directory: /home/zapotek/.rvm/gems/ruby-2.4.0-preview2/gems/ox-2.4.5/ext/ox
make "DESTDIR=" clean

current directory: /home/zapotek/.rvm/gems/ruby-2.4.0-preview2/gems/ox-2.4.5/ext/ox
make "DESTDIR="
compiling base64.c
compiling builder.c
compiling cache.c
compiling cache8.c
compiling dump.c
In file included from /home/zapotek/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby.h:33:0,
                 from cache8.h:9,
                 from dump.c:13:
dump.c: In function ‘dump_obj’:
/home/zapotek/.rvm/rubies/ruby-2.4.0-preview2/include/ruby-2.4.0/ruby/ruby.h:1182:33: warning: implicit declaration of function ‘rb_struct_const_ptr’ [-Wimplicit-function-declaration]
 #define RSTRUCT_PTR(st)         rb_struct_const_ptr(st)
                                 ^
dump.c:775:18: note: in expansion of macro ‘RSTRUCT_PTR’
      VALUE beg = RSTRUCT_PTR(obj)[0];
                  ^
dump.c:775:34: error: subscripted value is neither array nor pointer nor vector
      VALUE beg = RSTRUCT_PTR(obj)[0];
                                  ^
dump.c:776:34: error: subscripted value is neither array nor pointer nor vector
      VALUE end = RSTRUCT_PTR(obj)[1];
                                  ^
dump.c:777:35: error: subscripted value is neither array nor pointer nor vector
      VALUE excl = RSTRUCT_PTR(obj)[2];
                                   ^
dump.c:797:21: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
      for (i = 0, vp = RSTRUCT_PTR(obj); i < cnt; i++, vp++) {
                     ^
dump.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-self-assign’
cc1: warning: unrecognized command line option ‘-Wno-constant-logical-operand’
cc1: warning: unrecognized command line option ‘-Wno-parentheses-equality’
cc1: warning: unrecognized command line option ‘-Wno-tautological-compare’
Makefile:241: recipe for target 'dump.o' failed
make: *** [dump.o] Error 1

make failed, exit code 2
```

**Comment by ohler55** [comment]
I'll do some checking but if structs are gone that could take some rework to handle bot the new and the old.

**Comment by ohler55** [comment]
On line 1183 or ruby/ruby.h is this line
```c
#define RSTRUCT_PTR(st)         rb_struct_const_ptr(st)
```
The problem is that the function rb_struct_const_ptr() is never declared in any of the header files. This is a bug in the 2.4.0-preview2 release. There is nothing Ox can do about it. Well, there might be some hacks to get around it but the bottom line is it is a bug in the release and should be fixed. Check again on the next preview. For now it is appropriate to close the issue here. Maybe open one with the ruby team.

**Comment by Zapotek** [comment]
I haven't written C in about a decade but doesn't [this](https://github.com/ruby/ruby/blob/9e75488ac81f2e2f39336f34bd9c5360fdbdddb7/internal.h#L615) count?

**Comment by ohler55** [comment]
That would indeed count. I did not see that file in the preview2 release when using rbenv.

**Comment by Zapotek** [comment]
Seems to be in the preview2 branch as well: https://github.com/ruby/ruby/blob/v2_4_0_preview2/internal.h#L624

**Comment by ohler55** [comment]
I was looking at the repo. The internal.h is not provided outside the ruby build itself.  The include/ruby directory is for headers that C extensions can use that. So using rbenv for example, the includes are there but the not the sources once the version is installed.

**Comment by Zapotek** [comment]
So we're back to Ruby bug then or I misunderstood your explanation?

**Comment by ohler55** [comment]
Yup, you understood correctly.

**Comment by ohler55** [comment]
If it was a final release I'd be more concerned.

**Comment by Zapotek** [comment]
Fair enough.

Could I trouble you to open the issue on the Ruby tracker yourself?
I'm not sure I'd communicate the problem properly since I'm unfamiliar with the extension build system and the like.

**Comment by ohler55** [comment]
Thanks for keeping me on my toes. Looking at your other NULL character now.

**Comment by Zapotek** [comment]
Heh, [Arachni](https://github.com/Arachni/arachni) is a pretty good stress test. :)

**Comment by hsbt** [comment]
This was affected by https://bugs.ruby-lang.org/issues/9916 changes.

**Comment by ohler55** [comment]
I see that RSTRUCT GET/SET can be used. Is there a way to iterate the members of the structure?

**Comment by rushingfitness** [comment]
I'm on 2.4.1 and running into this. Is there a work around?
